name: Datacontract life cycle - POC

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
      DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
  
    steps:
      - name: checkout_repo
        uses: actions/checkout@v4

      - name: setup databricks_cli
        uses: databricks/setup-cli@v0.269.0

      - name: install python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: bundle validate
        run: databricks bundle validate

      - name: databricks bundle deploy
        run: |
          databricks bundle deploy --target dev --auto-approve \
            --var="DATACONTRACT_DATABRICKS_HOST=${{ secrets.DATABRICKS_HOST }}" \
            --var="DATACONTRACT_DATABRICKS_TOKEN=${{ secrets.DATABRICKS_TOKEN }}" \
            --var="DATACONTRACT_DATABRICKS_HTTP_PATH=${{ secrets.DATABRICKS_HTTP_PATH }}"

    